### ISSUE TITLE
OOM on eval

### ISSUE THREAD

**Issue by evolu8** [mhamilton723/STEGO#1]
I get the following running on a 16Gb card. Tried reducing setting values in the eval config. No joy. 

``` 
 "The default behavior for interpolate/upsample with float scale_factor changed "
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1088/1088 [04:06<00:00,  4.41it/s]
Error executing job with overrides: []
Traceback (most recent call last):
  File "eval_segmentation.py", line 144, in my_app
    outputs = {k: torch.cat(v, dim=0) for k, v in outputs.items()}
  File "eval_segmentation.py", line 144, in <dictcomp>
    outputs = {k: torch.cat(v, dim=0) for k, v in outputs.items()}
RuntimeError: [enforce fail at CPUAllocator.cpp:68] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 24053760000 bytes. Error code 12 (Cannot allocate memory)

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

**Comment by mhamilton723** [comment]
@evolu8 this should be fixed in master!

**Comment by chetanyaabhinav** [comment]
I am getting the same error while executing eval_segmentation.py ..

**Comment by yanxiangyi** [comment]
Same here.

**Comment by axkoenig** [comment]
Me too, with all the default settings of `eval_segmentation.py` I am getting OOM after about 12 mins (at approx. 70% of the COCO val set). Any hints?

Process memory quickly rises to 40GB
![Screen Shot 2023-01-12 at 12 04 09](https://user-images.githubusercontent.com/50868646/212050344-d18ce1a4-1a77-437f-982c-c384784e2ee3.png)

GPU memory looks good
![Screen Shot 2023-01-12 at 12 04 37](https://user-images.githubusercontent.com/50868646/212050452-e4820b3d-901b-4c2f-9e99-82ed024d5d38.png)

**Comment by axkoenig** [comment]
Ah, now I see. The code first computes all embeddings of all images and stores them in memory, and then CRF is done - which overflows my 40GB RAM.

**Comment by axkoenig** [comment]
another learning is that there are two branches: one called "main" the other "master". Master has a version of `eval_segmentation.py` that requires less memory
