### ISSUE TITLE
How to get Fig.3 (PR curves for DINO and MoCo V2) ?

### ISSUE THREAD

**Issue by vealocia** [mhamilton723/STEGO#10]
Hi, thanks for your interesting and excellent work!
I'm wondering how can I get the PR curves for DINO or MoCoV2 pre-trained weights, just like Fig.3 in paper. Can you give me any suggestions?

**Comment by Jumpat** [comment]
Hello! I wonder whether you have found out the solution. I' m still a little confusing about Fig.3😂

**Comment by Tsingularity** [comment]
hi @vealocia, just wondering could you give any instructions for plotting figure 3 using DINO feature? Thanks!
