### ISSUE TITLE
Gray images results

### ISSUE THREAD

**Issue by alien19** [mhamilton723/STEGO#14]
Hello @mhamilton723, thanks for your great efforts.
I have tried the demo_segmeentation on custom images with the provided models but the resulted images in the cluster folder are just in black and grey as shown. 
![ship_containers_human](https://user-images.githubusercontent.com/42179967/167600683-060d1983-a868-4e69-90cd-00fc143dbafa.png)
What might be the reason for that? or how can I visualize the results in colors as shown in your work?

Thanks in advance!

**Comment by mhamilton723** [comment]
Hey @alien19 this is as intended because the are PNG's with pixel values in the range of [0.....NumClasses]. To visualize them with a different colormap, you can load the images in python, and convert class numbers to colors of your choice.
