### ISSUE TITLE
Loss function issue

### ISSUE THREAD

**Issue by HeyGazz** [mhamilton723/STEGO#19]
Hi @mhamilton723,
i'm trying to implement your paper on Matlab, using your pipeline but with different net architectures and types of images. 

When i compute the correlation loss (eq 4, page 5) i get very big number (for example -4000 ). 
![Equation](https://user-images.githubusercontent.com/62962480/169781296-794389d1-01aa-46c9-8162-8db2c5f442ca.png)
The problem is when i sum all the elements of my 384x384x5  tensor even if every cells has a value between 0 and 1 the global sum tends to a big number. 

My question is, can you suggest me a way to resolve this issue?

**Comment by mhamilton723** [comment]
Hey @HeyGazz, we take the mean in most examples, I probably just forgot to add other 1/HWIJ factor in that equation
