### ISSUE TITLE
Environment issue

### ISSUE THREAD

**Issue by tanveer6715** [mhamilton723/STEGO#33]
Hi,
Thanks for your good work. I want to use this model for my own dataset but it took a long time when creating the environment for this repository. Anyone help me how can I create environment without facing any problem?

**Comment by Supgb** [comment]
Using the ```mamba``` package to install the environment instead of the ```conda``` can save a lot of time.

**Comment by FlyingYanglu** [comment]
Thanks a lot for posting the solution. In my case, my conda env creation froze at solving environment, but mamba installed everything properly.

**Comment by tanveer6715** [comment]
> Using the `mamba` package to install the environment instead of the `conda` can save a lot of time.

Thanks it works. I am closing this issue.
