### ISSUE TITLE
What is all_good_images in src/eval_segmentation.py used for?

### ISSUE THREAD

**Issue by frank-xwang** [mhamilton723/STEGO#4]
Hi, thanks for sharing your code! I found that you set all_good_images = [11, 32, 43, 52] for cityscapes. Could you please let me know why using [11, 32, 43, 52] and what all_good_images in src/eval_segmentation.py is used for? Thanks!

**Comment by abauville** [comment]
`all_good_images` are handpicked images for visualization purpose. It does not affect computation

**Comment by mhamilton723** [comment]
Yes @abauville is correct, those are just ones that i thought gave a reasonable spread of different behavior for our paper figures. Closing this issue
