### ISSUE TITLE
Training with custom dataset

### ISSUE THREAD

**Issue by tanveer6715** [mhamilton723/STEGO#46]
Hi,

Anyone here train STEGO using custom dataset? I tried to train the model with custom data but its accuracy and mIoU is "nan" as attached. Anyone who faced this problem please help me out. Thanks in advance.!!

![ACC](https://user-images.githubusercontent.com/84553134/183561625-57971d13-04a7-4bad-9fa4-f66ca12659ce.PNG)

**Comment by tanveer6715** [comment]
Sorry I solved this problem so I am closing this issue.

**Comment by gjackson1997** [comment]
> Sorry I solved this problem so I am closing this issue.

Hey, im running into the same issue. How did you fix it? thanks

**Comment by tanveer6715** [comment]
> > Sorry I solved this problem so I am closing this issue.
> 
> Hey, im running into the same issue. How did you fix it? thanks

Actrually when do not provide any labels so it cant compare validation prediction to the ground truth labels. If you want to check the mIoU or accuracy you need to provide ground truth labels for comparison.
