### ISSUE TITLE
Confused about the spatial centering implementation

### ISSUE THREAD

**Issue by aliasvishnu** [mhamilton723/STEGO#47]
As per my understanding, in this [code](https://github.com/mhamilton723/STEGO/blob/e20df22cf17c41ac78e3c8c75a3118ea87ff0a4c/src/modules.py#L330) for spatial centering, the operation `fd -= fd.mean([3, 4], keepdim = True)` should have been enough. 

Can you please correct my understanding/offer intuition into this segment of code - especially why `fd = fd - fd.mean() + old_mean` is done? Thank you.

**Comment by 1170300521** [comment]
I have the same question !

**Comment by mhamilton723** [comment]
It's been a little while but IIRC its so that you dont change the aggregate strength of the signal, aka the full mean (here old_mean). We still want positives to be more strong of an attractive force than negatives and this operation makes sure the aggregate strength remains unchanged
