### ISSUE TITLE
Environment stuck when installing

### ISSUE THREAD

**Issue by npielawski** [mhamilton723/STEGO#49]
Hello,

I tried setting up the environment with `conda env create -f environment.yml` but conda displays "Solving environment" indefinitely. I tested on two different machines (Ubuntu 18.04.4 LTS, and 20.04.4 LTS) and the same problem occurred. One attempt lasted 23 hours before I gave up.

Have you tried installing the environment? Does the installation process work for you?

Best,
Nicolas

**Comment by tanveer6715** [comment]
> Hello,
> 
> I tried setting up the environment with `conda env create -f environment.yml` but conda displays "Solving environment" indefinitely. I tested on two different machines (Ubuntu 18.04.4 LTS, and 20.04.4 LTS) and the same problem occurred. One attempt lasted 23 hours before I gave up.
> 
> Have you tried installing the environment? Does the installation process work for you?
> 
> Best, Nicolas

Hello I faced same problem. You should used mamba instead of conda and it works well. You should check #33 for reference.

Best,
Tanveer

**Comment by npielawski** [comment]
Thanks for your help, I used the solution from this issue at the end: https://github.com/mamba-org/mamba/issues/633 and it worked.

**Comment by tanveer6715** [comment]
> Thanks for your help, I used the solution from this issue at the end: [mamba-org/mamba#633](https://github.com/mamba-org/mamba/issues/633) and it worked.

Happy that your problem get solved. Do your have any idea about isssue #48. I have asked this question but getting no response?
