### ISSUE TITLE
How to choose the checkpoint without label information?

### ISSUE THREAD

**Issue by dongzhuoyao** [mhamilton723/STEGO#50]
Hi, I saw it in your code, you choose the checkpoint, [by 'test/cluster/mIOU' in pytorch-lightning. ](https://github.com/mhamilton723/STEGO/blob/e20df22cf17c41ac78e3c8c75a3118ea87ff0a4c/src/train_segmentation.py#L491)

But in your paper, you said that you didn't use any label information in training. 

Is there any misunderstanding for me?

Thanks.

similar issue:

https://github.com/mhamilton723/STEGO/issues/46

**Comment by mhamilton723** [comment]
The checkpointing saves both the top mIoU and the latest model. If I recall correctly we just use the model trained longest in results and you should as well. There's often not much difference in practice between the last model and the best model
