### ISSUE TITLE
What are the minimal hardware requirements?

### ISSUE THREAD

**Issue by codingbutstillalive** [mhamilton723/STEGO#53]
I would like to set up a minimal test case and compute segmentations for a few images on my 2018 Macbook (without a Nvidia GPU). Is it worth trying, or will I need other hardware resources?

The paper says that the Segmentation head on top is very lightweight.

**Comment by mhamilton723** [comment]
I ran on a NVIDIA V-100 (if memory serves me correctly). You can adjust the batch sizes so things fit on your GPUs. The segmentation head is a small nonlinear mode, so the total cost of the evaluation is not much more than DINO itself. Training is a different story, and to get reasonable batch sizes you need a reasonable GPU or multiple GPUs.
