### ISSUE TITLE
Train on my custom dataset with no labels

### ISSUE THREAD

**Issue by chendaozai** [mhamilton723/STEGO#56]
Hi! Thank you for your amazing work!
I want to run the ```train_segmentation.py``` code, but I don't have labels. What do I need to change in the validation part(such as ```validation_step()```, ```validation_epoch_end()```) of the trainer?

**Comment by mhamilton723** [comment]
Thanks for reaching out! Please follow the instructions here and omit the label directory

https://github.com/mhamilton723/STEGO#bringing-your-own-data
