### ISSUE TITLE
there is a problem when I set crop_type to "five"

### ISSUE THREAD

**Issue by chendaozai** [mhamilton723/STEGO#6]
Hi, thanks for sharing your code!
There is a problem when I set crop_type to "five". As is shown in picture.
![图片](https://user-images.githubusercontent.com/55949813/164969392-c243a408-dd25-40ed-a9f7-19af80830ffa.png)

**Comment by MY-LIU100101** [comment]
I think you should run crop_datasets.py to generate cropped images first.

**Comment by chendaozai** [comment]
> 

Thanks for the tip！
