### ISSUE TITLE
Precompute KNNS Error

### ISSUE THREAD

**Issue by Holmes2002** [mhamilton723/STEGO#64]
Hi I train with my dataset. My dataset has 9 classes but I adjust in topk =7 why it still error ?
RuntimeError: selected index k out of range

**Comment by mhamilton723** [comment]
Im not quite sure i have enough info to give you a good fix here. Could you provide more info?

**Comment by Holmes2002** [comment]
I solved it. Tks for your cmt !

**Comment by krishnaadithya** [comment]
@Holmes2002  how did you fix this? 

I am trying to train with my custom dataset and the classes =5 

I get his error: 
all_nns.append(torch.topk(pairwise_sims, 30)[1])
RuntimeError: selected index k out of range

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by yukun80** [comment]
@mhamilton723 @krishnaadithya I have the same problem, is the parameter setting of topk wrong? Looking forward to your reply
