### ISSUE TITLE
Model checkpointing only saving epoch 0

### ISSUE THREAD

**Issue by Holmes2002** [mhamilton723/STEGO#66]
Why I run model I just receive epoch 0 ?? Where the orthers

**Comment by mhamilton723** [comment]
I have the following checkpointing logic set up::

```
 ModelCheckpoint(
                dirpath=join(checkpoint_dir, name),
                every_n_train_steps=400,
                save_top_k=2,
                monitor="test/cluster/mIoU",
                mode="max",
            )
```
Perhaps your dataset is so large you didnt leave epoch 0 yet.

**Comment by Holmes2002** [comment]
I solved it. Tks for your cmt !

**Comment by FJGEODEV** [comment]
> I solved it. Tks for your cmt !

Could you please describe how you solved it? I got similar issue.
Thanks.
