### ISSUE TITLE
Fine-tuned Model

### ISSUE THREAD

**Issue by Holmes2002** [mhamilton723/STEGO#67]
Many issue when using cluster algorithm, such as  backgound same color with our labels , brightness difference of the same label, ...
I think we should use Contrastive to learn feature of total images. Then add classifiers and train with labeled dataset. Is any one do this and answer for me ?

**Comment by mhamilton723** [comment]
@Holmes2002 im ot quite sure what you mean here. Is there something you think the cluster probe is not capturing in your data? Try varying the number of clusters to see if your dataset naturally has more or less. Also iyou could clarify your question that would be a big help!

**Comment by Holmes2002** [comment]
I solved it. Tks for your cmt !
