### ISSUE TITLE
Loss linear is None

### ISSUE THREAD

**Issue by Holmes2002** [mhamilton723/STEGO#68]
Hi, I have trained with my dataset. I trained with 20k images and everything was fine but I'm training with 70k images and linear losss are NONE. 
Why ?

**Comment by Holmes2002** [comment]
Oh, I see . I trained with labels so loss linear is not None. If we train without labels, loss linear will be None, right ?

**Comment by mhamilton723** [comment]
Yes @Holmes2002 the linear probe needs labels to train so if your dataset doesn't include labels it won't train those pieces.
