### ISSUE TITLE
enviroment error about pytorch lighting

### ISSUE THREAD

**Issue by chendaozai** [mhamilton723/STEGO#69]
I use pytorch 1.7 and pytorch lighting 0.8.5, but there is a problem that `TypeError: __init__() got an unexpected keyword argument 'every_n_train_steps'`. I want to know which lighting is available？

**Comment by KennyChen880127** [comment]
I'm success to use pytorch-lightning==1.5.10, maybe you can try it!

**Comment by chendaozai** [comment]
@KennyChen880127  Thanks！
