### ISSUE TITLE
Add to README Instructions on using demo_segmentation.py?

### ISSUE THREAD

**Issue by timothyjchurchill** [mhamilton723/STEGO#7]
Hello!  Could you add to the README instructions on how to try out a pretrained model on a new image/dataset?  Would that be done through modifying demo_config.yml and using demo_segmentation.py?  Sorry for the dumb question.  Thank you!

**Comment by maxjeblick** [comment]
A colab example notebook may also be helpful to try things out easily.

**Comment by alien19** [comment]
Hi @timothyjchurchill, I have tried the demo_segmentation script by just `python demo_segmentation.py` form inside STEGO/src and before that I had to edit the path parameters in the demo_config.yml.

Hope you solved it!

**Comment by mhamilton723** [comment]
@maxjeblick added a  quick colab example, hopefully will be able to build it out more in the next few weeks

**Comment by maxjeblick** [comment]
Thanks a lot, appreciate it!

**Comment by Lance4Liu** [comment]
> Hi @timothyjchurchill, I have tried the demo_segmentation script by just `python demo_segmentation.py` form inside STEGO/src and before that I had to edit the path parameters in the demo_config.yml.
> 
> Hope you solved it!

@alien19 Hello! I also changed the models path of demo_config.yml (to one of the checkpoints files we saved when we ran train_segment.py) and ran demo_segment.py, but my Results were a blob of black. There is no desired effect.
Could you please tell me how to modify demo_config.yml in more detail? For example, what should model_path change? And how many epochs should it run? I ran 50 or so epochs and it didn't work as expected.
