### ISSUE TITLE
Training on own data without labels

### ISSUE THREAD

**Issue by IdoZach** [mhamilton723/STEGO#8]
Hi, I would like to train on my own data, without any labels. 
When running `precompute_knns.py` I keep running into issues related to missing images or image formats for the labels, which I do not have. What should I do?
Thanks.

**Comment by mhamilton723** [comment]
Hey @IdoZach, what is your error message i will try to repro

**Comment by evolu8** [comment]
If training without labels I found not creating a labels folder was the way forward. The instructions did not make this super clear. Might be worth a note.

**Comment by mhamilton723** [comment]
Thank you for that tip @evolu8, i have updated the docs
