### ISSUE TITLE
Solving environment gets killed on Ubuntu 22.04

### ISSUE THREAD

**Issue by atharvadeore999** [mhamilton723/STEGO#83]
Please suggest a solution to create environment using yaml file, as it doesn't get created after installing mamba too

**Comment by colt18** [comment]
`mamba env create -f environment.yml` did it for me under ubuntu 22.04. However, I made some modifications for python 3.7. Use it with precaution but for me it works smoothly.
[environment.zip](https://github.com/mhamilton723/STEGO/files/11445829/environment.zip)

**Comment by atharvadeore999** [comment]
> `mamba env create -f environment.yml` did it for me under ubuntu 22.04. However, I made some modifications for python 3.7. Use it with precaution but for me it works smoothly.
> [environment.zip](https://github.com/mhamilton723/STEGO/files/11445829/environment.zip)
> 

Can you please tell me what changes you made in python

**Comment by colt18** [comment]
I mean env file was meant for python 3.6.9. I changed it to 3.7 and changed versions of other packages for compatilibity. You just need to create env with the file I attached.

**Comment by atharvadeore999** [comment]
OK, Thank you

**Comment by nono-zz** [comment]
@colt18 Thanks, your 3.7 environment file works smoothly for me. Just `mamba` install the `cpu` version `pytorch` for me in default. I had to use
```
mamba install "pytorch=*=*cuda*" pytorch==1.10.1 torchvision==0.11.2 torchaudio==0.10.1 cudatoolkit=11.3 -c pytorch -c conda-forge
```
in the command line again to force the cuda version installation
