### ISSUE TITLE
Creating conda environment failing

### ISSUE THREAD

**Issue by smohammad-de** [mhamilton723/STEGO#9]
Unable to create conda environment using environment.yml file on ubuntu.

It is stuck in solving environment. 

Pls check

**Comment by SMSD75** [comment]
I have the same issue.

**Comment by Dont-Care-Didnt-Ask** [comment]
Me too.

**Comment by PazAranyi** [comment]
Hi,
I had the same issue, and I solved it by adding the next two lines to the "environment.yml" file:
under pip, add:
"
  - setuptools==59.5.0
  -pyDeprecate==0.3.1
"
I hope it could help the others.

**Comment by mhamilton723** [comment]
thank you @PazAranyi  I will add this to the setup!
